repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--fix, --extend-select=E501, --line-length=100]
      - id: ruff-format
        args: [--line-length=100]

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run ty check
        language: system
        types_or: [python, pyi]
        pass_filenames: false
